# Generated by Django 4.0 on 2022-01-26 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories_verified', models.CharField(choices=[('automotive', 'AUTOMOTIVE'), ('beauty', 'BEAUTY'), ('business', 'BUSINESS'), ('engineering', 'ENGINEERING'), ('entertainment', 'ENTERTAINMENT'), ('financial', 'FINANCIAL'), ('health', 'HEALTH'), ('history', 'HISTORY'), ('language', 'LANGUAGE'), ('politics', 'POLITICS'), ('programming', 'PROGRAMMING'), ('psychology', 'PYSCHOLOGY'), ('residential consruction', 'RESIDENTIAL CONSTRUCTION'), ('science', 'SCIENCE')], default='', max_length=30)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='accounts.user')),
            ],
        ),
    ]
