# Generated by Django 4.0 on 2022-01-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquire_me', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories_verified',
            new_name='categories',
        ),
    ]
