# Generated by Django 4.0 on 2022-01-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire_me', '0007_alter_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('Automotive', 'AUTOMOTIVE'), ('Beauty', 'BEAUTY'), ('Business', 'BUSINESS'), ('Engineering', 'ENGINEERING'), ('Entertainment', 'ENTERTAINMENT'), ('Financial', 'FINANCIAL'), ('Health', 'HEALTH'), ('History', 'HISTORY'), ('Language', 'LANGUAGE'), ('Politics', 'POLITICS'), ('Programming', 'PROGRAMMING'), ('Psychology', 'PYSCHOLOGY'), ('Construction/DIY', 'CONSTRUCTION/DIY'), ('Science', 'SCIENCE')], default='', max_length=30),
        ),
    ]
