# Generated by Django 4.0 on 2022-01-29 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquire_me', '0009_alter_post_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorylist', to='inquire_me.post')),
            ],
        ),
    ]
