# Generated by Django 4.0 on 2022-01-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire_me', '0010_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_list',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
