# Generated by Django 4.0 on 2022-02-03 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquire_me', '0012_remove_category_slug_remove_category_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='all_categories',
        ),
    ]
