# Generated by Django 4.0 on 2022-01-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories_verified',
            field=models.CharField(choices=[('automotive', 'AUTOMOTIVE'), ('beauty', 'BEAUTY'), ('business', 'BUSINESS'), ('engineering', 'ENGINEERING'), ('entertainment', 'ENTERTAINMENT'), ('financial', 'FINANCIAL'), ('health', 'HEALTH'), ('history', 'HISTORY'), ('language', 'LANGUAGE'), ('politics', 'POLITICS'), ('programming', 'PROGRAMMING'), ('psychology', 'PYSCHOLOGY'), ('residential construction', 'RESIDENTIAL CONSTRUCTION'), ('science', 'SCIENCE')], default='', max_length=30),
        ),
    ]
