# Generated by Django 4.0 on 2022-02-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='flag',
            field=models.IntegerField(choices=[(1, 'Standard Account'), (2, 'Pro Account')], default=1),
        ),
    ]
