# Generated by Django 4.0 on 2022-02-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usertype_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_doc',
            field=models.FileField(default=None, upload_to='media/files/'),
        ),
    ]
