# Generated by Django 4.0 on 2022-02-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_user_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_doc',
        ),
    ]
